### PR TITLE
#53: Model extractor can't parse fully qualified types (closes #53)

### LINKED ISSUE #53: Model extractor can't parse fully qualified types
## description
Fully qualified types are not parsed by metarpheus. We should parse them and return the latest path part.

## how to reproduce
- `case class Foo(bar: some.package.Bar)`

### PR DESCRIPTION
**Pull request by gabro**
Closes #53

### tests performed
unit tests

### CODE REVIEW

File: extractor/extractors.scala [hunk 1]
```diff
@@ -58,6 +58,7 @@ package object extractors {
       intermediate.Type.Name(name.value)
     case scala.meta.Type.Apply(name: scala.meta.Type.Name, args) =>
       intermediate.Type.Apply(name.value, args.map(tpeToIntermediate))
+    case scala.meta.Type.Select(_, t) => tpeToIntermediate(t)
```
Comment (bytecodeguru) [inline extractor/extractors.scala]: Elegant solution with a recursive call ❤️
